apiVersion: v1
kind: Service
metadata:
  name: {{ template "solarwinds-k8s-challange.fullname" . }}
  labels:
    app: {{ template "solarwinds-k8s-challange.name" . }}
    chart: {{ template "solarwinds-k8s-challange.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    app: {{ template "solarwinds-k8s-challange.name" . }}
    release: {{ .Release.Name }}