apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Chart.Name}}
  labels:
    app: {{.Chart.Name}}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    release: {{ .Release.Name }}
data:
  NAME: {{.Values.username}}
