# Default values for k8schl.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
minikubeEp: "<minikube IP>:80"

app:
  port: 3000
  # Use this to declare the name displayed from the app.
  displayName: matt
  replicaCount: 1

image:
  repository: k8schl-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  protocol: TCP

ingress:
  enabled: true
  annotations:
    #kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/ssl-redirect: "false"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
